// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=Verdict"; DO NOT EDIT.

package schema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VerdictBenign-0]
	_ = x[VerdictTelemetry-1]
	_ = x[VerdictMalicious-2]
}

const _Verdict_name = "VerdictBenignVerdictTelemetryVerdictMalicious"

var _Verdict_index = [...]uint8{0, 13, 29, 45}

func (i Verdict) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Verdict_index)-1 {
		return "Verdict(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Verdict_name[_Verdict_index[idx]:_Verdict_index[idx+1]]
}
