// SPDX-License-Identifier: Apache-2.0

// Code generated by "stringer -type=Action ./internal/policy"; DO NOT EDIT.

package policy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionForward-0]
	_ = x[ActionAllow-1]
	_ = x[ActionBlock-2]
}

const _Action_name = "ActionForwardActionAllowActionBlock"

var _Action_index = [...]uint8{0, 13, 24, 35}

func (i Action) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Action_index)-1 {
		return "Action(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Action_name[_Action_index[idx]:_Action_index[idx+1]]
}
